# Generated by Django 3.0.3 on 2020-03-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='friend',
            table='friend',
        ),
        migrations.AlterModelTable(
            name='swiped',
            table='swiped',
        ),
    ]
