# Generated by Django 3.0.3 on 2020-03-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0002_auto_20200311_1545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('uid1', 'uid2')},
        ),
    ]
