# Generated by Django 3.0.3 on 2020-03-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0003_auto_20200311_1651'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swiped',
            unique_together={('uid', 'sid')},
        ),
    ]
